//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using Xunit;

[assembly: System.Reflection.AssemblyCompanyAttribute("MGroup.Solvers.Distributed.Tests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("MGroup.Solvers.Distributed.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("MGroup.Solvers.Distributed.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.


// The following will prevent XUnit from running tests in parallel. Normally it should not be necessary, but up until 10/12/2018
// it was not worth the effort to make the classes used in some tests thread-safe.
[assembly: CollectionBehavior(DisableTestParallelization = true)]
